export const HOST = "https://digipaybackend.herokuapp.com/"
export const CHANGE_ROLE = "CHANGE_ROLE";
export const DATA_LOADING = "DATA_LOADING";

export const ERROR_AGENCE = "ERROR_AGENCE";
export const GET_AGENCES = "GET_AGENCES";
export const AGENCE_ONLINE = "AGENCE_ONLINE";
export const AGENCE_STATUS_LOADING = "AGENCE_STATUS_LOADING";
export const AGENCE_STATUS_ERROR = "AGENCE_STATUS_ERROR";
export const UPDATE_SOLDE = "UPDATE_SOLDE";

export const SUCCESS_TRANS = "SUCCESS_TRANS";
export const ERROR_TRANS = "ERROR_TRANS";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const HISTORY_TRANSACTIONS = "HISTORY_TRANSACTIONS";
export const ADD_TRANSFERT = "ADD_TRANSFERT";
export const ADD_RETRAIT = "ADD_RETRAIT";
export const ADD_RECHARGE = "ADD_RECHARGE";
export const ADD_PAIEMENT = "ADD_PAIEMENT";
export const ADD_PAYBACK = "ADD_PAYBACK";
export const GET_TRANSFERT = "GET_TRANSFERT";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";

export const ERROR_COMP = "ERROR_COMP";
export const GET_COMPENSATIONS = "GET_COMPENSATIONS";
export const ADD_COMPENSATION = "ADD_COMPENSATION";

export const ERROR_CLIENT = "ERROR_CLIENT";
export const GET_CLIENTS = "GET_CLIENTS";
export const ADD_CLIENT = "ADD_CLIENT";

//export const ERROR_CLIENT_DIGIPAY = "ERROR_CLIENT_DIGIPAY";
//export const CHECK_CLIENT_DIGIPAY = "CHECK_CLIENT_DIGIPAY";
export const UPDATE_SOLDE_CLIENT_DIGIPAY = "UPDATE_SOLDE_CLIENT_DIGIPAY";

export const ERROR_NOTIF = "ERROR_NOTIF";
export const GET_NOTIFS = "GET_NOTIFS";
export const SUCCESS_NOTIF = "SUCCESS_NOTIF";

export const ERROR_EMPLOYE = "ERROR_EMPLOYE";
export const GET_EMPLOYES = "GET_EMPLOYES";

export const AUTH_LOADING = "AUTH_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAN_SESSION = "CLEAN_SESSION";
export const TOKEN_EXPIRED = "TOKEN_EXPIRED";

export const UPDATE_PROFIL_FAIL = "UPDATE_PROFIL_FAIL";
export const UPDATE_VENDOR_SUCCESS = "UPDATE_VENDOR_SUCCESS";
export const UPDATE_CLIENT_DIGIPAY_SUCCESS = "UPDATE_CLIENT_DIGIPAY_SUCCESS";
export const UPDATE_EMPLOYE_SUCCESS = "UPDATE_EMPLOYE_SUCCESS";
export const UPDATE_RESPONSABLE_SUCCESS = "UPDATE_RESPONSABLE_SUCCESS";
export const UPDATE_AGENT_SUCCESS = "UPDATE_AGENT_SUCCESS";

